### ISSUE TITLE
badgeify

### ISSUE THREAD

**Issue by ivarconr** [finn-no/unleash-client-node#4]

**Comment by Andersos** [comment]
What badges were you thinking?

**Comment by ivarconr** [comment]
I was thinking about code-climate. Only thing missing is the coverage stuff.

**Comment by ivarconr** [comment]
Maybe @jarib can help set-up coveralls. I seems to be failing my attempt.

**Comment by ivarconr** [comment]
Hmz seems like it is working after all!
