### ISSUE TITLE
Remove "node" from package name?

### ISSUE THREAD

**Issue by phillipj** [finn-no/unleash-client-node#7]
There is really no need to have "node" in the actual module name. This is also one of few tips npm has about package names: https://docs.npmjs.com/files/package.json#name

The only place "-node" could be mentioned is in the github repo name IMO.

**Comment by ivarconr** [comment]
great input, agreed! 

Is it possible to unpublish a published npm-module?

**Comment by phillipj** [comment]
Yupp, should be as simple as
```bash
$ npm unpublish
```

As a sidenote, npm advices module authors to set a module as deprecated (via `npm deprecate`) rather than unpublishing, as someone might depend on these modules in production. That would produce deprecation warnings when installing the module, rather than failing hard. But that shouldnt be a problem for a just published module ofcourse :)

**Comment by ivarconr** [comment]
done: https://www.npmjs.com/package/unleash-client
